#ifndef COIN_ENCODINGS_H
#define COIN_ENCODINGS_H

#define BITCOIN_BASE58_CHARS "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"

#define DEFAULT_BASE58_CHARS BITCOIN_BASE58_CHARS

#endif // COIN_ENCODINGS_H
